export type AcquisitionStage = 'identified'|'initial_contact'|'owner_validation'|'property_validation'|'documentation'|'negotiation'|'commercial_review'|'legal_review'|'agreement_preparation'|'signing'|'payment_closing'|'acquisition_complete'|'on_hold'|'withdrawn';
export type Property = { id:string; organization_id:string; project_id:string; property_reference:string; title_number:string|null; tax_declaration:string|null; lot_number:string|null; area_hectares:number|null; municipality:string|null; province:string|null; barangay:string|null; acquisition_stage:AcquisitionStage; acquisition_status:string; assigned_negotiator_id:string|null; assigned_manager_id:string|null; legal_status:string; documentation_status:string; payment_status:string; readiness_percent:number; risk:'low'|'medium'|'high'; project_code?:string; project_name?:string; negotiator_name?:string|null; manager_name?:string|null; };
export type Project = { id:string; organization_id:string; code:string; name:string; description:string|null; status:string; acquisition_target:number|null; manager_user_id:string|null; starts_on:string|null; target_completion_on:string|null; created_at:string; updated_at:string; };
/** Same VITE_API_BASE_URL as organizationApi (/api/v1). Live ops paths are prefixed with /ops. */
const apiBase = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/,'') ?? '';
export const operationsApiMode = apiBase ? 'live' : 'demo';
export const DEMO_ORGANIZATION_ID = '2cb1ec8c-2fc4-47b9-99ec-bb1e7d64a91f';
type AuthBridge = { getAccessToken: () => Promise<string> };
declare global { interface Window { __BIZCAIAOS_AUTH__?: AuthBridge } }
async function request<T>(path:string, init?:RequestInit):Promise<T>{
  if (!apiBase) throw new Error('Live API mode is not configured');
  const auth=window.__BIZCAIAOS_AUTH__; if(!auth) throw new Error('Authentication provider is not connected');
  const token=await auth.getAccessToken(); const response=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init?.headers}});
  const payload=await response.json(); if(!response.ok) throw new Error(payload.error?.message ?? 'Request failed'); return payload.data as T;
}
const demoOrg=DEMO_ORGANIZATION_ID;
let demoProjects:Project[]=[{id:'6c8e5a14-2b89-4d1d-a2f0-8f9b0a2f0001',organization_id:demoOrg,code:'NCP-01',name:'North Corridor Program',description:'Primary acquisition program',status:'active',acquisition_target:125000000,manager_user_id:null,starts_on:'2026-01-01',target_completion_on:'2026-12-31',created_at:'2026-01-01T00:00:00Z',updated_at:'2026-09-20T00:00:00Z'}];
let demoProperties:Property[]=[
{id:'70000000-0000-4000-8000-000000000001',organization_id:demoOrg,project_id:demoProjects[0].id,property_reference:'NCP-00102',title_number:'TCT-102',tax_declaration:'TD-102',lot_number:'Lot 102',area_hectares:2.4,municipality:'Calamba',province:'Laguna',barangay:'Canlubang',acquisition_stage:'negotiation',acquisition_status:'active',assigned_negotiator_id:null,assigned_manager_id:null,legal_status:'under_review',documentation_status:'in_review',payment_status:'not_started',readiness_percent:68,risk:'medium',project_code:'NCP-01',project_name:'North Corridor Program',negotiator_name:'Luis Reyes'},
{id:'70000000-0000-4000-8000-000000000002',organization_id:demoOrg,project_id:demoProjects[0].id,property_reference:'NCP-00118',title_number:'TCT-118',tax_declaration:'TD-118',lot_number:'Lot 118',area_hectares:1.8,municipality:'Calamba',province:'Laguna',barangay:'Pansol',acquisition_stage:'commercial_review',acquisition_status:'active',assigned_negotiator_id:null,assigned_manager_id:null,legal_status:'clear',documentation_status:'complete',payment_status:'not_started',readiness_percent:84,risk:'low',project_code:'NCP-01',project_name:'North Corridor Program',negotiator_name:'Luis Reyes'},
{id:'70000000-0000-4000-8000-000000000003',organization_id:demoOrg,project_id:demoProjects[0].id,property_reference:'NCP-00131',title_number:null,tax_declaration:'TD-131',lot_number:'Lot 131',area_hectares:3.1,municipality:'Calamba',province:'Laguna',barangay:'Bucal',acquisition_stage:'documentation',acquisition_status:'active',assigned_negotiator_id:null,assigned_manager_id:null,legal_status:'blocked',documentation_status:'missing',payment_status:'not_started',readiness_percent:42,risk:'high',project_code:'NCP-01',project_name:'North Corridor Program',negotiator_name:'Luis Reyes'}];
export const operationsApi={
 async listProjects(orgId:string){ if(operationsApiMode==='live') return request<Project[]>(`/ops/projects?organizationId=${orgId}`); return demoProjects.filter(p=>p.organization_id===orgId); },
 async createProject(input:Partial<Project>&{organization_id:string;code:string;name:string}){ if(operationsApiMode==='live') return request<Project>('/ops/projects',{method:'POST',body:JSON.stringify({organizationId:input.organization_id,code:input.code,name:input.name,description:input.description,status:input.status,acquisitionTarget:input.acquisition_target,managerUserId:input.manager_user_id,startsOn:input.starts_on,targetCompletionOn:input.target_completion_on})}); const p={...demoProjects[0],...input,id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()} as Project; demoProjects=[p,...demoProjects]; return p; },
 async listProperties(orgId:string, filters?:{projectId?:string;stage?:AcquisitionStage;search?:string}){ if(operationsApiMode==='live'){const q=new URLSearchParams({organizationId:orgId,...filters}); return request<Property[]>(`/ops/properties?${q}`);} return demoProperties.filter(p=>p.organization_id===orgId).filter(p=>!filters?.projectId||p.project_id===filters.projectId).filter(p=>!filters?.stage||p.acquisition_stage===filters.stage).filter(p=>!filters?.search||`${p.property_reference} ${p.lot_number??''} ${p.municipality??''}`.toLowerCase().includes(filters.search.toLowerCase())); },
 async getProperty(id:string){ if(operationsApiMode==='live') return request<Property>(`/ops/properties/${id}`); return demoProperties.find(p=>p.id===id)!; },
 async createProperty(input:{organizationId:string;projectId:string;propertyReference:string;municipality?:string;province?:string;barangay?:string;areaHectares?:number;acquisitionStage?:AcquisitionStage;risk?:string}){ if(operationsApiMode==='live') return request<Property>('/ops/properties',{method:'POST',body:JSON.stringify(input)}); const p={id:crypto.randomUUID(),organization_id:input.organizationId,project_id:input.projectId,property_reference:input.propertyReference,title_number:null,tax_declaration:null,lot_number:null,area_hectares:input.areaHectares??null,municipality:input.municipality??null,province:input.province??null,barangay:input.barangay??null,acquisition_stage:input.acquisitionStage??'identified',acquisition_status:'active',assigned_negotiator_id:null,assigned_manager_id:null,legal_status:'unknown',documentation_status:'not_started',payment_status:'not_started',readiness_percent:0,risk:(input.risk??'medium') as 'low'|'medium'|'high',project_code:demoProjects.find(x=>x.id===input.projectId)?.code,project_name:demoProjects.find(x=>x.id===input.projectId)?.name,negotiator_name:null}; demoProperties=[p,...demoProperties]; return p; },
 async updateProperty(id:string,input:Record<string,unknown>){ if(operationsApiMode==='live') return request<Property>(`/ops/properties/${id}`,{method:'PATCH',body:JSON.stringify(input)}); const index=demoProperties.findIndex(p=>p.id===id); if(index<0) throw new Error('Property not found'); demoProperties[index]={...demoProperties[index],...Object.fromEntries(Object.entries(input).map(([k,v])=>[({acquisitionStage:'acquisition_stage',acquisitionStatus:'acquisition_status',readinessPercent:'readiness_percent',legalStatus:'legal_status',documentationStatus:'documentation_status',paymentStatus:'payment_status'} as Record<string,string>)[k]??k,v]))}; return demoProperties[index]; },
 async dashboard(orgId:string){ if(operationsApiMode==='live') return request<any>(`/ops/dashboard?organizationId=${orgId}`); const p=demoProperties.filter(x=>x.organization_id===orgId); return {total:String(p.length),active:String(p.filter(x=>x.acquisition_status==='active').length),negotiation:String(p.filter(x=>x.acquisition_stage==='negotiation').length),blocked:String(p.filter(x=>x.legal_status==='blocked'||x.risk==='high').length),ready:String(p.filter(x=>x.readiness_percent>=80&&x.acquisition_status==='active').length),stages:[]}; }
};
